# 
# Vagrantfile per un singolo nodo (node), con Oracle Java. 
# 

VAGRANTFILE_API_VERSION = "2"

# utente di default per Ubuntu trusty 64 VirtualBox
vagrant_user = "vagrant" 

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # Configurazioni comuni.

    # Ubuntu trusty 64 VirtualBox.
    config.vm.box = "ubuntu/trusty64"
    # config.vm.box_url = "http://files.vagrantup.com/ubuntu/trusty64.box"

    # folder per i progetti Asw (/home/vagrant/projects)
    config.vm.synced_folder "../../projects/", "/home/#{vagrant_user}/projects", :mount_options => ["dmode=777", "fmode=777"]

    # folder per le risorse condivise per gli ambienti Asw (/home/vagrant/shared/resources e /home/vagrant/shared/scripts) 
    config.vm.synced_folder "../shared/", "/home/#{vagrant_user}/shared", :mount_options => ["dmode=777", "fmode=777"]

    #
    # Configurazione del nodo "node", che prevede: 
    # - Oracle Java SDK 8 
    #
    config.vm.define "node" do |node|
        node.vm.hostname = "node"    
        node.vm.network "private_network", ip: "10.11.1.201", virtualbox__intnet: true

        node.vm.provider "virtualbox" do |v| 
            v.memory = 1024 
			v.cpus = 1
        end 

        node.vm.network "forwarded_port", guest: 22, host: 2222, id: 'ssh', auto_correct: true 
        node.ssh.forward_agent = true
 
        # provisioning con bash 
        node.vm.provision :shell, :inline => 'apt-get update'
        node.vm.provision :shell, env: {"VAGRANT_USER" => "#{vagrant_user}"}, path: "../shared/scripts/setup-java.sh"
  
        node.vm.provision :shell, 
            inline: "echo  'configurazione nodo node completata'"

    end

end
